import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: "#050505",
    },
    container: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 96,
        gap: 20,
    },
    header: {
        paddingBottom: 16,
        paddingHorizontal: 4,
    },
    title: {
        fontSize: 28,
        fontWeight: "700",
        color: "#FAFAFA",
        letterSpacing: 0.5,
    },
    subtitle: {
        marginTop: 6,
        color: "#A1A1AA",
        fontSize: 15,
    },
    card: {
        backgroundColor: "#09090B",
        borderWidth: 1,
        borderColor: "#18181B",
        borderRadius: 16,
        padding: 14,
        gap: 12,
    },
    profileRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 16,
        paddingVertical: 4,
    },
    avatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: "#18181B",
        borderWidth: 1,
        borderColor: "#27272A",
        justifyContent: "center",
        alignItems: "center",
    },
    avatarText: {
        color: "#FAFAFA",
        fontSize: 20,
        fontWeight: "700",
        letterSpacing: 1,
    },
    profileName: {
        fontSize: 18,
        fontWeight: "600",
        color: "#FAFAFA",
        marginBottom: 4,
    },
    profileEmail: {
        color: "#71717A",
        fontSize: 14,
    },
    chevronText: {
        color: "#3F3F46",
        fontSize: 20,
    },
    sectionTitle: {
        marginBottom: 10,
        marginLeft: 4,
        color: "#71717A",
        fontSize: 13,
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    rowCenter: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        flexShrink: 1,
    },
    rowTitle: {
        fontSize: 16,
        fontWeight: "500",
        color: "#E4E4E7",
        marginBottom: 2,
    },
    rowSubtitle: {
        color: "#71717A",
        fontSize: 13,
    },
    divide: {
        gap: 0,
        paddingHorizontal: 0,
        paddingVertical: 4,
    },
    linkRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: "#18181B",
    },
    badge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        fontSize: 12,
        overflow: "hidden",
        fontWeight: "600",
    },
    badgeOutline: {
        backgroundColor: "rgba(239, 68, 68, 0.1)",
        color: "#EF4444",
        borderWidth: 1,
        borderColor: "rgba(239, 68, 68, 0.2)",
    },
    badgeSolid: {
        backgroundColor: "rgba(16, 185, 129, 0.1)",
        color: "#10B981",
        borderWidth: 1,
        borderColor: "rgba(16, 185, 129, 0.2)",
    },
    buttonGhost: {
        borderWidth: 1,
        borderColor: "#18181B",
        backgroundColor: "#09090B",
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: "center",
        marginTop: 10,
    },
    buttonGhostText: {
        color: "#EF4444",
        fontWeight: "600",
        fontSize: 16,
    },
    settingToggleRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: "#18181B",
        gap: 12,
    },
    circleIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#18181B",
        alignItems: "center",
        justifyContent: "center",
    },
    // Offline Banner Overrides
    offlineBanner: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: "rgba(239, 68, 68, 0.1)",
        borderWidth: 1,
        borderColor: "rgba(239, 68, 68, 0.25)",
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginBottom: 12,
    },
    offlineBannerText: {
        color: "#FCA5A5",
        fontSize: 13,
        flexShrink: 1,
        marginRight: 12,
    },
    offlineUpdateButton: {
        backgroundColor: "rgba(239, 68, 68, 0.2)",
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        minWidth: 72,
        alignItems: "center",
    },
    offlineUpdateButtonText: {
        color: "#EF4444",
        fontWeight: "600",
        fontSize: 13,
    },
});

export default styles;